# @file: parlor/.circleci/config.yml
---
version: 2

jobs:
  build:
    docker:
      - image: dexai2/drake-torch:cpu-nightly-ros-latest

    steps:
      - run:
          name: setup
          command: |
            echo "In setup . . ."
            ls -lahFG /opt
            mkdir -p ~/.ssh
            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ~/.ssh/known_hosts
            # set up lcmtypes for include
            mkdir -p ~/catkin_ws/src/
            cd ~/catkin_ws/src/
            git clone git@github.com:DexaiRobotics/robot_msgs.git
            ln -s ~/catkin_ws/src/robot_msgs/include/lcmtypes/robot_msgs /usr/include/robot_msgs
      - checkout:
      - run:
          name: build and test
          command: |
            echo "In build and test: building project . . ."
            ls ~
            cd ~/project
            git submodule update --init --recursive
            ./setup.sh 2 1 1 0 ### 3 => make -j 2; 1 => build tests; 1 => run ctest; 0 => not debug
