# @file: parlor/.circleci/config.yml
---
version: 2

jobs:
  build:
    docker:
      - image: dexai2/drake-pytorch:cpu-stable-ros-latest

    steps:
      - run:
          name: setup
          command: |
            echo "In setup . . ."
            ls -lahFG /opt
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            # set up lcmtypes for include
            mkdir -p ~/catkin_ws/src/
            cd ~/catkin_ws/src/
            git clone git@github.com:DexaiRobotics/robot_msgs.git
            export ROS_MASTER_URI=http://localhost:11311
            export ROS_HOSTNAME=localhost
            source /opt/ros/${ROS_DISTRO}/setup.bash
            cd ~/catkin_ws/
            catkin_make
      - checkout:
      - run:
          name: build and test
          command: |
            echo "In build and test: building project . . ."
            cd ~/project
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git submodule update --init --recursive
            source $HOME/catkin_ws/devel/setup.bash
            ./setup.sh 2 1 1 0 ### 3 => make -j 2; 1 => build tests; 1 => run ctest; 0 => not debug
