# @file: parlor/.circleci/config.yml
---
version: 2

jobs:
  build:
    docker:
      - image: dmsj/drake-torch:latest #sprax/drax-momap:0.2.9

    steps:
      - run:
          name: setup
          command: |
            echo "In setup: cloning repositories: dracula, . . ."
            ls -lahFG /opt
            mkdir -p ~/.ssh
            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ~/.ssh/known_hosts
            cd ~
            # git clone git@github.com:eigenteam/eigen-git-mirror.git eigen3
            # cd eigen3 && git checkout 3.3.5
            # mkdir build && cd build && cmake .. && make install 
            # echo ">>>> Installed Eigen3 <<<<"
            # cd ~
            
            echo "======================== COMMENCED cloning dracula ========================"
            git clone git@github.com:DexaiRobotics/dracula.git
            echo "======================== COMPLETED cloning dracula ========================"
            ls -lahFG .
            cd ..

      - checkout

      - run:
          name: build and test
          command: |
            echo "In build and test: build pre-reqs and dracula . . ."
            cd ~/dracula
            ./setup.sh 2 0 0 0
            cd ~/project
            ./setup.sh 2 1 1 0 ### 3 => make -j 2; 1 => build tests; 1 => run ctest; 0 => not debug
